// Local events: no external sync or background reminders.
(()=>{const KEY='apb-calendar-events-v1',grid=document.getElementById('calGrid');if(!grid)return;let events;try{events=JSON.parse(localStorage.getItem(KEY)||'[]')}catch{events=[]}
const key=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const dialog=document.createElement('dialog');dialog.className='apb-dialog calendar-editor';dialog.innerHTML='<form method="dialog"><h3 id="eventHeading">События</h3><div id="eventList"></div><label>Название<input id="eventTitle" required maxlength="160"></label><label>Время<input id="eventTime" type="time"></label><label>Описание<textarea id="eventNote" maxlength="3000" rows="3"></textarea></label><div class="appearance-actions"><button type="button" id="eventCancel">Закрыть</button><button type="submit" class="primary-btn">Сохранить</button></div></form>';document.body.append(dialog);
let selected='',editing=null;const title=dialog.querySelector('#eventTitle'),time=dialog.querySelector('#eventTime'),note=dialog.querySelector('#eventNote');
function save(){localStorage.setItem(KEY,JSON.stringify(events));decorate();list()}
function list(){const root=dialog.querySelector('#eventList');root.replaceChildren();events.filter(e=>e.date===selected).sort((a,b)=>(a.time||'').localeCompare(b.time||'')).forEach(e=>{const row=document.createElement('div');row.className='event-item';const text=document.createElement('button');text.type='button';text.textContent=(e.time?e.time+' · ':'')+e.title;text.onclick=()=>{editing=e.id;title.value=e.title;time.value=e.time||'';note.value=e.note||''};const del=document.createElement('button');del.type='button';del.textContent='×';del.setAttribute('aria-label','Удалить событие');del.onclick=()=>{events=events.filter(x=>x.id!==e.id);if(editing===e.id){editing=null;title.value='';time.value='';note.value=''}save()};row.append(text,del);root.append(row)})}
function open(date){selected=date;editing=null;title.value='';time.value='';note.value='';dialog.querySelector('#eventHeading').textContent='События · '+date.split('-').reverse().join('.');list();dialog.showModal();title.focus()}
dialog.querySelector('#eventCancel').onclick=()=>dialog.close();dialog.querySelector('form').onsubmit=e=>{e.preventDefault();if(!title.value.trim())return;const item={id:editing||crypto.randomUUID(),date:selected,title:title.value.trim(),time:time.value,note:note.value.trim()};events=events.filter(x=>x.id!==item.id);events.push(item);save();dialog.close();if(typeof toast==='function')toast('Событие сохранено','ok')};
function decorate(){const base=new Date(),offset=typeof calOffset==='number'?calOffset:0;grid.querySelectorAll('.cal-day:not(.other)').forEach(cell=>{const day=Number(cell.textContent);if(!day)return;const date=key(new Date(base.getFullYear(),base.getMonth()+offset,day));cell.dataset.date=date;cell.tabIndex=0;cell.setAttribute('role','button');const found=events.filter(e=>e.date===date);cell.classList.toggle('has-events',found.length>0);cell.title=found.length?found.map(e=>(e.time?e.time+' ':'')+e.title).join('\n'):'Двойной клик — создать событие';cell.setAttribute('aria-label',date+(found.length?' · событий: '+found.length:''))})}
grid.addEventListener('dblclick',e=>{if(e.button!==0)return;const c=e.target.closest('[data-date]');if(c)open(c.dataset.date)});grid.addEventListener('keydown',e=>{const c=e.target.closest('[data-date]');if(c&&e.key==='Enter'){e.preventDefault();open(c.dataset.date)}});new MutationObserver(decorate).observe(grid,{childList:true});decorate();})();
