// APB offline E2E profile container — no network and no cloud.
(()=>{
const ALLOWED_KEYS=["apb-theme","apb-appearance-v8","apb-themes","apb-search-engine","apb-home-widgets-v9","apb-ui","apb-idea-deck-v8"];
const settings=document.getElementById("settings");if(!settings||!window.__TAURI__)return;
const box=document.createElement("section");box.className="profile-sync-card";box.setAttribute("aria-labelledby","profileSyncTitle");
box.innerHTML=`<h3 id="profileSyncTitle">Локальная E2E-синхронизация</h3><p class="hint">Создаёт один зашифрованный файл с закладками, темами и настройками. Облако и сеть не используются.</p><div class="profile-sync-fields"><label><span>Фраза контейнера</span><input id="profileSyncPass" type="password" autocomplete="new-password" minlength="10"></label><label><span>Повторите фразу</span><input id="profileSyncConfirm" type="password" autocomplete="new-password" minlength="10"></label></div><div class="row"><button class="primary-btn" id="profileSyncExport">🔐 Экспортировать профиль</button><button class="ghost-btn" id="profileSyncImport">Открыть контейнер</button><input id="profileSyncFile" type="file" accept=".apbprofile,application/json" hidden></div><p class="hint" id="profileSyncStatus" role="status" aria-live="polite"></p>`;
const updateHeading=[...settings.querySelectorAll('.panel-subtitle')].find(x=>x.textContent.trim()==='Обновления');updateHeading?.before(box);
const invoke=window.__TAURI__.core.invoke,$=id=>document.getElementById(id),status=(m,bad=false)=>{const e=$("profileSyncStatus");e.textContent=m;e.classList.toggle("error",bad)};
function phrase(requireConfirm=true){const p=$("profileSyncPass").value,c=$("profileSyncConfirm").value;if(p.length<10)throw new Error("Минимум 10 символов");if(requireConfirm&&p!==c)throw new Error("Фразы не совпадают");return p}
function clientState(){const o={};for(const k of ALLOWED_KEYS){const v=localStorage.getItem(k);if(v!==null)o[k]=v}return o}
$("profileSyncExport").onclick=async()=>{try{status("Шифруем профиль…");const path=await invoke("profile_container_export",{passphrase:phrase(true),clientState:clientState()});status("Готово: "+path);$("profileSyncPass").value=$("profileSyncConfirm").value=""}catch(e){status(String(e).replace(/^Error:\s*/,""),true)}};
$("profileSyncImport").onclick=()=>$("profileSyncFile").click();
$("profileSyncFile").onchange=async e=>{const f=e.target.files?.[0];e.target.value="";if(!f)return;try{status("Расшифровываем и проверяем контейнер…");const data=await invoke("profile_container_decrypt",{container:await f.text(),passphrase:phrase(false)});const state=data.client_state||{};for(const k of ALLOWED_KEYS)if(Object.prototype.hasOwnProperty.call(state,k)&&typeof state[k]==="string")localStorage.setItem(k,state[k]);const current=await invoke("bookmarks_tree");const urls=new Set((current.items||[]).map(x=>x.url));
const folderMap=new Map(),pending=[...(data.folders||[])];let rounds=0;
while(pending.length&&rounds++<20){let moved=0;for(let i=pending.length-1;i>=0;i--){const f=pending[i],parent=f.parent_id?folderMap.get(f.parent_id):null;if(f.parent_id&&!parent)continue;const made=await invoke("bookmark_folder_create",{name:String(f.name||"Импорт"),parentId:parent||null});folderMap.set(f.id,made.id);pending.splice(i,1);moved++}if(!moved)break}
let added=0;for(const bm of data.bookmarks||[]){if(!bm?.url||urls.has(bm.url))continue;await invoke("add_bookmark",{title:String(bm.title||bm.url),url:String(bm.url),tags:Array.isArray(bm.tags)?bm.tags.map(String):[],note:bm.note==null?null:String(bm.note),folderId:bm.folder_id?folderMap.get(bm.folder_id)||null:null});urls.add(bm.url);added++}
if(data.settings?.theme)await invoke("settings_theme_save",{theme:String(data.settings.theme),resolved:null}).catch(()=>{});if(data.settings?.search_engine)await invoke("settings_search_save",{engine:String(data.settings.search_engine)}).catch(()=>{});
status(`Импортировано закладок: ${added}. Темы и настройки применятся после перезапуска.`);$("profileSyncPass").value=$("profileSyncConfirm").value=""}catch(err){status(String(err).replace(/^Error:\s*/,""),true)}};
})();
