// APB v8.3 custom-only color picker: no native browser popup.
(()=>{let active=null,h=220,s=.5,v=.8,drag=null;const clamp=(n,a=0,b=1)=>Math.max(a,Math.min(b,n));
function hsvToHex(H,S,V){const c=V*S,x=c*(1-Math.abs((H/60)%2-1)),m=V-c;let r=0,g=0,b=0;if(H<60)[r,g,b]=[c,x,0];else if(H<120)[r,g,b]=[x,c,0];else if(H<180)[r,g,b]=[0,c,x];else if(H<240)[r,g,b]=[0,x,c];else if(H<300)[r,g,b]=[x,0,c];else[r,g,b]=[c,0,x];return '#'+[r,g,b].map(n=>Math.round((n+m)*255).toString(16).padStart(2,'0')).join('')}
function clean(x){x=String(x||'').trim().replace(/^#/,'').replace(/[^0-9a-f]/gi,'').slice(0,6);return x.length===3?x.split('').map(c=>c+c).join(''):x}
function hexToHsv(value){const x=clean(value).padEnd(6,'0'),n=parseInt(x,16),r=((n>>16)&255)/255,g=((n>>8)&255)/255,b=(n&255)/255,max=Math.max(r,g,b),min=Math.min(r,g,b),d=max-min;let H=0;if(d){if(max===r)H=60*(((g-b)/d)%6);else if(max===g)H=60*((b-r)/d+2);else H=60*((r-g)/d+4)}if(H<0)H+=360;return[H,max?d/max:0,max]}
const pop=document.createElement('div');pop.className='apb-color-picker hidden';pop.innerHTML=`<div class="cp-head"><div><b>Цвет</b><small id="cpTarget"></small></div><button id="cpClose" type="button">×</button></div><div class="cp-sv" id="cpSv"><i id="cpCursor"></i></div><input class="cp-hue" id="cpHue" type="range" min="0" max="360"><div class="cp-bottom"><span class="cp-preview" id="cpPreview"></span><label>#<input id="cpHex" maxlength="6" spellcheck="false"></label></div><div class="cp-clipboard"><button id="cpCopy" type="button">Копировать</button><button id="cpPaste" type="button">Вставить</button><small id="cpMessage"></small></div><div class="cp-swatches">${['#ffffff','#d7d7dc','#ff6575','#ff9f43','#ffd166','#43c17a','#22d3ee','#4c8dff','#8b5cf6','#ec5cff','#111318','#000000'].map(c=>`<button type="button" data-c="${c}" style="--c:${c}" title="${c}"></button>`).join('')}</div>`;document.body.append(pop);
const sv=pop.querySelector('#cpSv'),cur=pop.querySelector('#cpCursor'),hue=pop.querySelector('#cpHue'),hex=pop.querySelector('#cpHex'),preview=pop.querySelector('#cpPreview'),target=pop.querySelector('#cpTarget'),msg=pop.querySelector('#cpMessage');
function draw(push=true){const color=hsvToHex(h,s,v);sv.style.setProperty('--hue',`hsl(${h} 100% 50%)`);cur.style.left=s*100+'%';cur.style.top=(1-v)*100+'%';hue.value=String(h);hex.value=color.slice(1).toUpperCase();preview.style.background=color;if(active){active.value=color;active.style.setProperty('--picked',color);if(push)active.dispatchEvent(new Event('input',{bubbles:true}))}}
function setHex(value){const x=clean(value);if(x.length!==6)return false;[h,s,v]=hexToHsv(x);draw();return true}function point(e){const r=sv.getBoundingClientRect();s=clamp((e.clientX-r.left)/r.width);v=1-clamp((e.clientY-r.top)/r.height);draw()}
sv.onpointerdown=e=>{drag=e.pointerId;sv.setPointerCapture(drag);point(e)};sv.onpointermove=e=>{if(drag===e.pointerId)point(e)};sv.onpointerup=e=>{if(drag===e.pointerId)drag=null};hue.oninput=()=>{h=+hue.value;draw()};hex.oninput=()=>setHex(hex.value);pop.querySelectorAll('[data-c]').forEach(b=>b.onclick=()=>setHex(b.dataset.c));
async function copy(){const value='#'+hex.value;try{await navigator.clipboard.writeText(value);msg.textContent='Скопировано'}catch{hex.select();document.execCommand?.('copy');msg.textContent='Скопировано'}setTimeout(()=>msg.textContent='',1200)}async function paste(){try{const value=await navigator.clipboard.readText();msg.textContent=setHex(value)?'Цвет вставлен':'Неверный HEX'}catch{msg.textContent='Нажмите Ctrl+V в поле HEX'}setTimeout(()=>msg.textContent='',1600)}pop.querySelector('#cpCopy').onclick=copy;pop.querySelector('#cpPaste').onclick=paste;
function close(){if(active)active.dispatchEvent(new Event('change',{bubbles:true}));active=null;pop.classList.add('hidden');pop.classList.remove('open')}pop.querySelector('#cpClose').onclick=close;function open(input){active=input;[h,s,v]=hexToHsv(input.value||'#000000');target.textContent=input.closest('label')?.querySelector('span')?.textContent||input.title||'Цвет';pop.classList.remove('hidden');pop.classList.remove('open');void pop.offsetWidth;pop.classList.add('open');const r=input.getBoundingClientRect(),w=300;pop.style.left=Math.min(innerWidth-w-12,Math.max(12,r.right-w))+'px';let y=r.bottom+8;if(y+430>innerHeight)y=Math.max(12,r.top-410);pop.style.top=y+'px';draw(false)}
function convert(){document.querySelectorAll('input[type="color"]').forEach(input=>{input.type='text';input.readOnly=true;input.dataset.apbColor='1';input.setAttribute('aria-haspopup','dialog');input.style.setProperty('--picked',input.value)})}convert();
document.addEventListener('click',e=>{const input=e.target.closest?.('[data-apb-color]');if(input){e.preventDefault();e.stopImmediatePropagation();open(input);return}if(!pop.classList.contains('hidden')&&!pop.contains(e.target))close()},true);document.addEventListener('keydown',e=>{const input=e.target.closest?.('[data-apb-color]');if(input&&(e.key==='Enter'||e.key===' ')){e.preventDefault();open(input)}});window.addEventListener('resize',close);window.addEventListener('scroll',close,true);
})();
