// APB v8.2 — crisp interactive canvas effects with incremental density.
(()=>{
  const TAU=Math.PI*2,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  function rgb(value){let x=String(value||'#7c8cff');if(/^#[0-9a-f]{3}$/i.test(x))x='#'+[...x.slice(1)].map(c=>c+c).join('');if(!/^#[0-9a-f]{6}$/i.test(x))x='#7c8cff';return[parseInt(x.slice(1,3),16),parseInt(x.slice(3,5),16),parseInt(x.slice(5,7),16)]}
  const rgba=(c,a)=>`rgba(${c[0]},${c[1]},${c[2]},${a})`;
  function renderer(kind,host,initial){
    const canvas=document.createElement('canvas');canvas.className=`apb-fx-canvas fx-${kind}`;canvas.style.filter='none';host.append(canvas);
    const isNetwork=kind==='network';
    const linkCanvas=isNetwork?document.createElement('canvas'):null;
    if(linkCanvas){linkCanvas.className=`apb-fx-canvas fx-link-${kind}`;linkCanvas.style.filter='none';host.prepend(linkCanvas);}
    const ctx=canvas.getContext('2d',{alpha:true,desynchronized:true});
    const lctx=linkCanvas?linkCanvas.getContext('2d',{alpha:true,desynchronized:true}):null;
    if(lctx){lctx.setTransform(1,0,0,1,0,0);}let opt=initial,w=1,h=1,dpr=1,nodes=[],raf=0,last=0,reported=-1,linkAt=-1;const pointer={x:-9999,y:-9999,active:false};
    const makeNode=()=>({x:Math.random()*w,y:Math.random()*h,vx:(Math.random()-.5)*(kind==='network'?.22:.34),vy:(Math.random()-.5)*(kind==='network'?.22:.34),r:.7+Math.random()*2.1,z:.35+Math.random()*.65,phase:Math.random()*TAU});
    function desired(){const density=clamp(Number(opt.density)||1,.2,2),scale=clamp(Math.sqrt((w*h)/(1280*720)),.65,1.45);if(kind==='network')return clamp(Math.round((20+density*65)*scale),22,210);if(kind==='particles')return clamp(Math.round((34+density*100)*scale),40,310);return clamp(Math.round(3+density*4.5),4,12)}
    function report(count){if(reported===count)return;reported=count;document.dispatchEvent(new CustomEvent('apb:fx-count',{detail:{type:kind,count,label:kind==='waves'?`${count} волн`:`${count} объектов`}}))}
    function reconcile(reset=false){const target=desired();if(reset)nodes=[];while(nodes.length<target)nodes.push(makeNode());if(nodes.length>target)nodes.length=target;report(target)}
    function resize(){const r=host.getBoundingClientRect();w=Math.max(1,r.width);h=Math.max(1,r.height);dpr=Math.min(devicePixelRatio||1,1.6);canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);canvas.style.width=w+'px';canvas.style.height=h+'px';ctx.setTransform(dpr,0,0,dpr,0,0);if(linkCanvas){linkCanvas.width=Math.round(w*dpr);linkCanvas.height=Math.round(h*dpr);linkCanvas.style.width=w+'px';linkCanvas.style.height=h+'px';if(lctx)lctx.setTransform(dpr,0,0,dpr,0,0)}reconcile(false)}
    function influence(p,strength,orbit=false){if(!opt.interactive||!pointer.active)return;const dx=pointer.x-p.x,dy=pointer.y-p.y,dist=Math.hypot(dx,dy),radius=Math.min(240,Math.max(130,Math.min(w,h)*.25));if(dist<radius&&dist>2){const f=(1-dist/radius)*strength;if(orbit){p.vx+=(-dy/dist)*f+dx/dist*f*.25;p.vy+=(dx/dist)*f+dy/dist*f*.25}else{p.vx-=dx/dist*f;p.vy-=dy/dist*f}}}
    function move(p,speed){p.x+=p.vx*speed;p.y+=p.vy*speed;if(p.x<-8)p.x=w+8;if(p.x>w+8)p.x=-8;if(p.y<-8)p.y=h+8;if(p.y>h+8)p.y=-8;p.vx*=.998;p.vy*=.998}
    function drawNetwork(t,dt){const a=rgb(opt.primary),b=rgb(opt.secondary),speed=clamp(Number(opt.speed)||.55,.1,1.5)*dt/16.67,intensity=clamp(Number(opt.intensity)||.7,.1,1),limit=135,doLinks=t-linkAt>=40;if(doLinks)linkAt=t;for(const p of nodes){influence(p,.012);p.vx+=Math.sin(t*.00035+p.phase)*.0011;p.vy+=Math.cos(t*.00028+p.phase)*.001;move(p,speed);p.vx=clamp(p.vx,-.55,.55);p.vy=clamp(p.vy,-.55,.55)}if(lctx&&doLinks){lctx.clearRect(0,0,w,h);lctx.lineWidth=1;for(let i=0;i<nodes.length;i++){const p=nodes[i];for(let j=i+1;j<nodes.length;j++){const q=nodes[j],dx=p.x-q.x,dy=p.y-q.y,d2=dx*dx+dy*dy;if(d2>limit*limit)continue;lctx.strokeStyle=rgba(a,(1-Math.sqrt(d2)/limit)*.28*intensity);lctx.beginPath();lctx.moveTo(p.x,p.y);lctx.lineTo(q.x,q.y);lctx.stroke()}if(pointer.active&&opt.interactive){const d=Math.hypot(pointer.x-p.x,pointer.y-p.y);if(d<170){lctx.strokeStyle=rgba(b,(1-d/170)*.38*intensity);lctx.beginPath();lctx.moveTo(p.x,p.y);lctx.lineTo(pointer.x,pointer.y);lctx.stroke()}}}}for(let i=0;i<nodes.length;i++){const p=nodes[i];ctx.fillStyle=rgba(b,(.45+.35*p.z)*intensity);ctx.beginPath();ctx.arc(p.x,p.y,p.r*(.65+.35*Math.sin(t*.0012+p.phase)),0,TAU);ctx.fill()}}
    function drawParticles(t,dt){const a=rgb(opt.primary),b=rgb(opt.secondary),speed=clamp(Number(opt.speed)||.55,.1,1.5)*dt/16.67,intensity=clamp(Number(opt.intensity)||.7,.1,1);for(let i=0;i<nodes.length;i++){const p=nodes[i];influence(p,.009,true);p.vx+=Math.sin(t*.00035+p.phase)*.0008;p.vy+=Math.cos(t*.00028+p.phase)*.0007;move(p,speed*(.45+p.z*.8));p.vx=clamp(p.vx,-.65,.65);p.vy=clamp(p.vy,-.65,.65);const c=i%3?b:a,twinkle=.55+.45*Math.sin(t*.0015+p.phase);ctx.fillStyle=rgba(c,(.28+.58*p.z)*twinkle*intensity);ctx.beginPath();ctx.arc(p.x,p.y,p.r*(.55+p.z*.8),0,TAU);ctx.fill();if(p.z>.78){ctx.strokeStyle=rgba(c,.16*intensity);ctx.beginPath();ctx.moveTo(p.x-p.vx*18,p.y-p.vy*18);ctx.lineTo(p.x,p.y);ctx.stroke()}}}
    function drawWaves(t){const a=rgb(opt.primary),b=rgb(opt.secondary),speed=clamp(Number(opt.speed)||.55,.1,1.5),intensity=clamp(Number(opt.intensity)||.7,.1,1),lines=desired();ctx.lineWidth=1.15;for(let k=0;k<lines;k++){const base=h*(.16+k*(.7/Math.max(1,lines-1))),amp=10+k*2.1,phase=t*.00042*speed+k*.72;ctx.beginPath();for(let x=-8;x<=w+8;x+=7){let y=base+Math.sin(x*.008+phase)*amp+Math.sin(x*.017-phase*.7)*amp*.35;if(opt.interactive&&pointer.active){const dx=x-pointer.x,near=Math.exp(-(dx*dx)/30000);y+=(pointer.y-base)*near*.18+Math.sin(phase*2)*near*9}x<0?ctx.moveTo(x,y):ctx.lineTo(x,y)}ctx.strokeStyle=rgba(k%2?a:b,(.09+k*.09/lines)*intensity);ctx.stroke()}}
    function frame(t){raf=requestAnimationFrame(frame);const dt=Math.min(34,t-(last||t));if(t-last<15)return;last=t;ctx.clearRect(0,0,w,h);if(kind==='network')drawNetwork(t,dt);else if(kind==='particles')drawParticles(t,dt);else drawWaves(t)}
    const pointerMove=e=>{const r=canvas.getBoundingClientRect();pointer.x=e.clientX-r.left;pointer.y=e.clientY-r.top;pointer.active=true},pointerLeave=()=>pointer.active=false;addEventListener('pointermove',pointerMove,{passive:true});addEventListener('pointerleave',pointerLeave,{passive:true});const observer=new ResizeObserver(resize);observer.observe(host);resize();raf=requestAnimationFrame(frame);
    return{update(next){const changed=Number(next.density)!==Number(opt.density);opt=next;if(changed)reconcile(false)},pause(){cancelAnimationFrame(raf)},resume(){cancelAnimationFrame(raf);last=0;linkAt=-1;raf=requestAnimationFrame(frame)},destroy(){cancelAnimationFrame(raf);observer.disconnect();removeEventListener('pointermove',pointerMove);removeEventListener('pointerleave',pointerLeave);canvas.remove();if(linkCanvas)linkCanvas.remove()}}
  }
  for(const kind of ['network','particles','waves'])window.APBFxRegistry.register(kind,(host,opt)=>renderer(kind,host,opt));
})();
